# Documentation configuration for Nginx-File-Directory.

INHERIT: .mkdocs-shared/shared/mkdocs.base.yml

site_name: 'Nginx File Directory'
site_description: 'The basic Nginx file directory page, as a simple HTML page.'
site_author: willtheorangeguy
site_url: https://williamvdg.me/Nginx-File-Directory/docs/

repo_url: https://github.com/willtheorangeguy/Nginx-File-Directory
repo_name: willtheorangeguy/Nginx-File-Directory
edit_uri: edit/main/docs/

copyright: Copyright &copy; willtheorangeguy

nav:
  - Home: index.md
  - 'Quickstart': 'quickstart.md'
  - 'Installation': 'installation.md'
  - 'Usage': 'usage.md'
  - 'Configuration': 'configuration.md'
  - 'Architecture': 'architecture.md'
  - 'Deployment': 'deployment.md'
  - 'FAQ': 'faq.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Roadmap': 'roadmap.md'
  - 'Nginx-File-Directory': 'internal/known-issues.md'
  - 'Privacy Policy': 'legal/privacy.md'
  - 'Terms and Conditions': 'legal/terms.md'
  - Changelog: changelog.md
  - License: license.md
  - Contributing: https://github.com/willtheorangeguy/.github/blob/main/CONTRIBUTING.md
  - Code of Conduct: https://github.com/willtheorangeguy/.github/blob/main/CODE_OF_CONDUCT.md
  - Security: https://github.com/willtheorangeguy/.github/blob/main/SECURITY.md

exclude_docs: |
  docs.instructions.md